### ISSUE TITLE
Tag to match GFDL_atmos_cubed_sphere

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/atmos_drivers#4]
**Is your feature request related to a problem? Please describe.**
Typically, the atmos_drivers and GFDL_atmos_cubed_sphere are checked out together and run as the component *atmos_dyn* at GFDL.  These two repositories should release tags at the same time.

**Describe the solution you'd like**
Once the documentation is complete (#3), tag master as [2020.01 just like GFDL_atmos_cubed_sphere](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/releases/tag/2020.01)

**Describe alternatives you've considered**

**Additional context**
This is what it looks like in a GFDL XML
```xml
    <component name="atmos_dyn" paths="atmos_drivers/coupled
                                       GFDL_atmos_cubed_sphere/driver/GFDL
                                       GFDL_atmos_cubed_sphere/model
                                       GFDL_atmos_cubed_sphere/model_nh_null
                                       GFDL_atmos_cubed_sphere/tools
                                       GFDL_atmos_cubed_sphere/GFDL_tools"
                                requires="fms atmos_phys">
      <source versionControl="git" root="https://github.com/NOAA-GFDL">
        <codeBase version="$(RELEASE)">atmos_drivers.git atmos_cubed_sphere.git</codeBase>

```

**Comment by bensonr** [comment]
@thomas-robinson I think the final atmos_cubed_sphere.git needs to be GFDL_atmos_cubed_sphere.git

**Comment by bensonr** [comment]
A 2020.01 pre-release tag has been created.  Please test
